vmware-tanzu/graph-framework-for-microservices

- compiler/example/datamodel/config/policy/policy.go
- compiler/example/output/_rendered_templates/nexus-gql/gqlgen.yml
- compiler/example/output/_rendered_templates/nexus-gql/graph/graphqlResolver.go
- compiler/example/output/_rendered_templates/nexus-gql/graph/schema.graphqls
- compiler/example/output/generated/nexus-gql/gqlgen.yml
- compiler/example/output/generated/nexus-gql/graph/generated/generated.go
- compiler/example/output/generated/nexus-gql/graph/graphqlResolver.go
- compiler/example/output/generated/nexus-gql/graph/model/models_gen.go
- compiler/example/output/generated/nexus-gql/graph/schema.graphqls
- compiler/example/output/generated/nexus-gql/graph/schema.resolvers.go
- compiler/pkg/generator/resolver_generator.go
- compiler/pkg/generator/template/graphql/schema.graphqls.tmpl
In graphql schema template we depend on resolver count being greater than 0, if it's zero schema for given node is not generated. For now resolver count was increased only if there was a child/link node defined, so when there weren't any child or node count was 0, so there schema was not resolved properly for custom queries.
Now increase resolver count also for custom queries so template is resolved properly when there is no child or link, but only custom queries in given node.
> NPT-599 Increase resolver count for custom queries

- .github/workflows/build.yml
- .github/workflows/release.yml
- cli/Makefile
- cli/pkg/common/global.go
- cli/pkg/common/repos.yaml
- cli/pkg/common/values.yaml
- cli/pkg/servicemesh/datamodel/build.go
- cli/pkg/servicemesh/upgrade/cli.go
- cli/pkg/servicemesh/version/update.go
- cli/pkg/servicemesh/version/version.go
- cli/pkg/utils/checks.go
currently, CLI and Compiler version has two different entities 
* removing NexusCLI and NexusCompiler versions from values.yml
* using BuildVERSION from go ldflags to store version
* create CLI binaries for Darwin,Linux(AMD64/ARM64) and store it on each release binaries
> NPT-619 Add single nexus version for compiler and CLI

- .github/ISSUE_TEMPLATE/bug_report.md
Current issue templates are using markdown as the means of getting input from the user. It is textual and the experience is very mundane.
Migrate issue templates to GitHub form schema for a better user experience while creating issues.
> 51 Use Github form schema in issue template

- cli/pkg/common/values.yaml
as we use plugin based mechanism to load graphql binaries as importable , we are seeing errors due to gofuzz package being incompatible with graphqlserver
bumping up to latest gofuzz (v1.2.0) in graphqlserver to make it compatible
bumping up nexus-runtime with latest graphql image
> NPT-545 Graphql server is build with different version of gofuzz package

- compiler/example/output/_rendered_templates/apis/config.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/_rendered_templates/apis/gns.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/_rendered_templates/apis/policypkg.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/_rendered_templates/apis/root.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/generated/apis/config.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/generated/apis/gns.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/generated/apis/policypkg.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/generated/apis/root.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/generated/crds/config_config.yaml
- compiler/example/output/generated/crds/config_domain.yaml
- compiler/example/output/generated/crds/gns_additionalgnsdata.yaml
- compiler/example/output/generated/crds/gns_gns.yaml
- compiler/example/output/generated/crds/gns_randomgnsdata.yaml
- compiler/example/output/generated/crds/policypkg_acpconfig.yaml
- compiler/example/output/generated/crds/policypkg_additionalpolicydata.yaml
- compiler/example/output/generated/crds/policypkg_randompolicydata.yaml
- compiler/example/test-utils/output-group-name-with-hyphen-datamodel/crd_generated/apis/config.tsm-tanzu.vmware.com/v1/types.go
- compiler/pkg/generator/types_generator.go
- compiler/pkg/parser/pkg.go
- compiler/pkg/parser/pkg_test.go
NPT-173: JSON and YAML tags are not added for nested structs
Nested struct fields in nexus.Node structs, are not populating correctly in CRD. Generated yaml and json files should use camelCase for their fields, which doesn't work if they are not specifically provided. 
This change automatically adds tags misssing tags, which solves the issue of case in output files
> NPT-173: JSON and YAML tags are not added for nested structs

- cli/get-nexus-cli.sh
Add script to download the nexus cli to User given Path or default path.
The design is captured here:  https://jira.eng.vmware.com/browse/NPT-678
Example command to download and execute the script:
`curl -fsSL https://raw.githubusercontent.com/vmware-tanzu/graph-framework-for-microservices/NPT-678-nexus-cli-install/cli/get-nexus-cli.sh -o get-nexus-cli.sh
To download the latest image
bash get-nexus-cli.sh
To download a specific version
bash get-nexus-cli.sh --version v0.0.134`
> [NPT-678] Add script to download and install nexus cli 

- gqlgen/graphql/executor/executor.go
- gqlgen/graphql/playground/playground.go
JIRA: https://jira.eng.vmware.com/browse/NPT-683
**PROBLEM:**
GraphQL playground throws the following error message and stacks when an empty query is executed
The response error message and stack were not at all relevant to the empty query case
```
{
"errors": [
{
"message": "Invalid AST Node: undefined.",
"stack": "Error: Invalid AST Node: undefined.\n    at o (https://cdn.jsdelivr.net/npm/graphiql@2.0.1/graphiql.min.js:1:195952)\n    at Le (https://cdn.jsdelivr.net/npm/graphiql@2.0.1/graphiql.min.js:1:233026)\n    at e.isSubscriptionWithName (https://cdn.jsdelivr.net/npm/graphiql@2.0.1/graphiql.min.js:29:466654)\n    at https://cdn.jsdelivr.net/npm/graphiql@2.0.1/graphiql.min.js:29:464369\n    at https://cdn.jsdelivr.net/npm/graphiql@2.0.1/graphiql.min.js:29:223596\n    at onClick …
```
> NPT-683: Graphql playground update

- docs/getting_started/Playground.md
Removed datamodel  docker pkg step, since the nexus datamodel build will do this step
> NPT-671: The `nexus datamodel build` should build docker image by default

- cli/get-nexus-cli.sh
closes #73 
For any reason `bash get-nexus-cli.sh` failed, the next re-try might fail if the previous docker is running. So added a step to remove the docker before creating new docker with nexus-cli
> NPT-695: Delete any docker with nexus-cli is

- compiler/example/output/_rendered_templates/nexus-client/client.go
- compiler/example/output/generated/nexus-client/client.go
- compiler/example/test-utils/output-group-name-with-hyphen-datamodel/crd_generated/nexus-client/client.go
- compiler/pkg/generator/client_generator.go
- compiler/pkg/generator/template/client.go.tmpl
- compiler/pkg/generator/template_renderers.go
- compiler/pkg/util/namers.go
- docs/getting_started/SubscribeAPI.md
Adding api subscribe feature in nexus-client library
nexus-client library will have:
1. Subscribe() method for all nexus node to create cache for the node, once Subscribe() is called for a nexus node, GET and List will be served from cache, this will reduce the number of calls on api-server and hence will reduce the load on api-server.
2. Unsubscribe() method to remove cache for the node(if Subscribe() has been called for the node).
3. SubscribeAll() to create cache for all the nexus nodes.
4. UnsubscribeAll() to remove cache for all the nexus nodes.
Also GET and LIST methods for all the nexus node are modified to look for the data into cache if the cache is present for the node and will return data from the cache, if cache is not present for the node then call will be made to the …
> NPT-550: API subscribe feature in nexus client-library

- compiler/example/output/_rendered_templates/nexus-gql/graph/graphqlResolver.go
- compiler/example/output/generated/nexus-gql/graph/graphqlResolver.go
- compiler/example/test-utils/output-group-name-with-hyphen-datamodel/crd_generated/nexus-gql/graph/graphqlResolver.go
- compiler/pkg/generator/template/graphql/graphqlResolver.go.tmpl
- docs/getting_started/SubscribeAPI.md
Use subscribe API feature of nexus-client library in graphql to create cache of nexus nodes and to reduce load on api-server
> NPT-728: Use subscribe API feature of nexus-client library in graphql

- cli/get-nexus-cli.sh
If the docker command fails while installing, it's silent and the script does not print errors due to redirection of stderr to null on the first use of docker command.
This change will make sure to validate docker is accessible and print out the error on screen if it's not.
> Adding a check for docker in the install script.

- docs/getting_started/Playground.md
All the getting started documents have hardcoded paths
mkdir -p $HOME/test-datamodel/orgchart && cd $HOME/test-datamodel/orgchart
As requested the paths are to be user-defined
export WORKDIR=$HOME/work/graph-test
mkdir -p $WORKDIR/test-datamodel/orgchart && cd $WORKDIR/test-datamodel/orgchart
> #74 NPT-696: Remove hardcoded paths from playground 

- compiler/example/test-utils/nexus-rest-api-gen-wrong-name/go.mod
- compiler/example/test-utils/nexus-rest-api-gen-wrong-name/go.sum
- compiler/example/test-utils/nexus-rest-api-gen-wrong-name/root.go
- compiler/pkg/parser/node_config.go
- compiler/pkg/parser/node_parser_test.go
- compiler/pkg/parser/pkg.go
[NPT-791] When nexus-rest-api-gen annotation var name is wrong, nexus compiler doesn't complain
This commit is to fail the compilation when nexus-rest-api-gen annotation var name is wrong.
> NPT-791: When nexus-rest-api-gen annotation var name is wrong, nexus compiler doesn't complain

- compiler/builder/Dockerfile
The builder stopped working because of openssh version
This change fixes this problem
> fix builder

- compiler/example/tests/go.mod
- compiler/example/tests/go.sum
- compiler/go.mod
- compiler/go.sum
- kube-openapi/go.mod
- kube-openapi/go.sum
github dependabot has flagged critical vulnerabilities with go-resftul
package < v2.16.0
This commit upgrade the package to version v2.16.0.
> #124 Upgrade go-restful package to address critical vulnerabilities

- nexus/nexus/nexus.go
This commit is to add new type `NexusGenericObject` in nexus pkg
This new type is needed for cosmos DM
> COSMOS-1086: Add new type NexusGenericObject in nexus pkg

- compiler/pkg/generator/template/client.go.tmpl
Fix issue in Delete{Node}ByName() method
Ignore Not Found error while deleting child/children of a node in DeleteNodeByName methods of nexus-client
> NPT-889: Fix issue in Delete{Node}ByName() method

- compiler/Makefile
- compiler/cmd/preparser/main.go
- compiler/pkg/parser/node_parser.go
- compiler/pkg/preparser/preparser.go
Updated the compiler to support the cosmos datamodel upgrdade
The preparser and node_parser were not skipping the ignoredDirs configured in config file(nexus.yaml)
Initialized the config object in cmd/preparser/main.go and added code to skip parsing of ignoredDirs in preparser.go and node_parser.go
> Npt 632 cosmos datamodel upgrade changes

- cli/get-nexus-cli.sh
Check added for valid tag version and log message added while Installing Nexus.
Example output:
For  'invalid reference format
The log will be as below:
bash cli/get-nexus-cli.sh --no-prompt
Unable to get the nexus image tag, Please contact Nexus Support
Valid case:
❯ bash cli/get-nexus-cli.sh --no-prompt
Downloading Nexus ...
Version: v0.0.162
Image repository: gcr.io/nsx-sm/nexus/nexus-cli
Directory: /usr/local/bin
Installing Nexus...
Nexus (v0.0.162) installed in /usr/local/bin/nexus
Run "nexus help" to get started
> [COSMOS-2218] Nexus Install script log improvements

- compiler/pkg/generator/template/client.go.tmpl
In Nexus SDK, the update method expect that the object metadata (along with the annotations and labels) be populated on the object before an update is called.
Nexus SDK should be able to infer the annotations and labels needs it and not need the app code to populate them for every update.
> COSMOS-2804: Nexus SDK should be able to infer the annotations and labels needs it and not need the app code to populate them

- compiler/example/output/_rendered_templates/apis/config.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/_rendered_templates/apis/gns.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/generated/apis/config.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/generated/apis/gns.tsm.tanzu.vmware.com/v1/types.go
- compiler/example/output/generated/crds/config_footypeabc.yaml
- compiler/example/output/generated/crds/gns_gns.yaml
- compiler/pkg/generator/types_generator.go
- compiler/pkg/openapi_generator/generator.go
CRD fields with graphql annotations were generated without json and yaml tags.
Changed the logic of building tag for fields. Now it will add json and yaml tags if they are missing.
> COSMOS-3251: Crd field generated in uppercase for field with nexus.NexusGenericObject type

- cli/pkg/servicemesh/runtime/uninstall.go
This commit removes a import of a closed source logging library from opensourced cli code.
There is a logging pacakge in the cli code based that should be referenced and used by other packages.
> 213 Remove import of closed source logging library
